;okulno=1019 verilen Say=19AB
	LIST P=16F84A
	INCLUDE "P16F84A.INC"
	CBLOCK H'20'
	a1,a2,b1,b2
ENDC
	BSF STATUS,5
	MOVLW H'03'
	MOVWF TRISA
	CLRF TRISB
	MOVLW H'06'
	MOVWF ADCON1
	BCF STATUS,5
	CLRF PORTB
ELDE_KONT_ALT
	MOVLW H'21'
	MOVWF a1 	; OKUL Numarası ALT BİTİ
	MOVLW H'AB'
	MOVWF B1	;verilen say no alt biti
	MOVLW H'10'
	MOVWF a2	;okul no üst biti 
	MOVLW H'11'
	MOVWF b2	;verilen say no üst biti 

	MOVF a1,W
	ADDWF b1,F
	BTFSC STATUS,C 	;elde durumu
	INCF a2,F	;varsa ustte bit'1' ekle	
	BTFSC PORTA,0
	GOTO ELDE_KONT_ALT
	BTFSS PORTA,0
	GOTO ELDE_KONT_ALT
	MOVF b1,W
	MOVWF PORTB
ELDE_KONT_UST
	MOVF a2,W
	ADDWF b2,F
	BTFSC PORTA,1
	GOTO ELDE_KONT_UST
	BTFSS PORTA,1
	GOTO ELDE_KONT_UST
	MOVF b2,W
	MOVWF PORTB
	GOTO ELDE_KONT_ALT
	END